# Generated by Django 4.2.2 on 2023-06-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categoriesofprodycts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesOfProdycts',
            new_name='CategoriesOfProducts',
        ),
    ]
