# Generated by Django 4.2.2 on 2023-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_unit',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
